ponto-de-coleta:
  path: /pontos-de-coleta
  controller: Coleta\Controller\ColetaController::index
  methods: [GET, OPTIONS]

admin_dashboard:
  path: /admin
  controller: Admin\Controller\DashboardController::index
  methods: [GET, OPTIONS]