services:
  _defaults:
    public: false
    autowire: true
    autoconfigure: true

  Coleta\:
    resource: '../../../src/Coleta/*'
    exclude: '../../../src/Coleta/{DependencyInjection,Entity,Migrations,Tests}'